services:
  - type: worker
    name: zenbot-highrise
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: cd bot && highrise bot:HigrhiseBot $HIGHRISE_ROOM_ID $HIGHRISE_TOKEN
    envVars:
      - key: HIGHRISE_TOKEN
        sync: false
      - key: HIGHRISE_ROOM_ID
        sync: false
